# Generated by Django 5.0.7 on 2024-11-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImpactEvaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('division_name', models.CharField(default='Unknown Division', max_length=255)),
                ('activity_title', models.CharField(default='Untitled Activity', max_length=255)),
                ('activity_date', models.DateField(blank=True, null=True)),
                ('venue', models.CharField(default='Unknown Venue', max_length=255)),
                ('objectives', models.TextField(default='Objectives not provided.')),
                ('Q1', models.CharField(choices=[(3, 'Clearly defined and achieved'), (2, 'Partially'), (1, 'Not Achieved')], default='Clearly defined and achieved', max_length=50)),
                ('Q2', models.CharField(choices=[(3, 'Very effectively'), (2, 'Moderately effectively'), (1, 'Ineffectively')], default='Very effectively', max_length=50)),
                ('Q3', models.CharField(choices=[(3, 'Excellently managed'), (2, 'Adequately managed'), (1, 'Poorly managed')], default='Excellently managed', max_length=50)),
                ('Q4', models.CharField(choices=[(3, 'Excellent support and assistance'), (2, 'Adequate support and assistance'), (1, 'Insufficient support and assistance')], default='Excellent support and assistance', max_length=50)),
                ('Q5', models.CharField(choices=[(3, 'Highly fostered engagement'), (2, 'Moderately fostered engagement'), (1, 'Minimally fostered engagement')], default='Highly fostered engagement', max_length=50)),
                ('Q6', models.CharField(choices=[(3, 'Significantly promoted awareness'), (2, 'Partially promoted awareness'), (1, 'Did not promote awareness')], default='Significantly promoted awareness', max_length=50)),
                ('Q7', models.CharField(choices=[(3, 'Strongly encouraged collaboration'), (2, 'Somewhat encouraged collaboration'), (1, 'Did not encourage collaboration')], default='Strongly encouraged collaboration', max_length=50)),
                ('Q8', models.CharField(choices=[(3, 'Highly engaged and participative'), (2, 'Moderately engaged and participative'), (1, 'Low engagement and participation')], default='Highly engaged and participative', max_length=50)),
                ('Q9', models.CharField(choices=[(3, 'Significant positive impact'), (2, 'Some positive impact'), (1, 'No discernible impact')], default='Significant positive impact', max_length=50)),
                ('Q10', models.CharField(choices=[(3, 'Very likely'), (2, 'Somewhat likely'), (1, 'Unlikely')], default='Very likely', max_length=50)),
                ('Q11', models.CharField(choices=[(3, 'Highly positive experience'), (2, 'Neutral experience'), (1, 'Negative experience')], default='Highly positive experience', max_length=50)),
                ('Q12_recommendations', models.TextField(default='No recommendations provided.')),
            ],
        ),
    ]
