# Generated by Django 5.0.7 on 2024-10-05 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models
from django.utils import timezone
from django.contrib.auth.hashers import make_password

def create_default_account(apps, schema_editor):
    Account = apps.get_model('api', 'Account')
    Account.objects.create(
        username="Anna",
        password=make_password("Anna"),  # Hash password
        accountType="Admin",
        department="Administration",
        position="Director",
        activationDate=timezone.now().date(),
        status="Active"
    )
class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=255, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('accountType', models.CharField(max_length=255)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('position', models.CharField(max_length=255, null=True)),
                ('activationDate', models.DateField()),
                ('deactivationDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(create_default_account),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('award_title', models.CharField(max_length=255)),
                ('awardee', models.CharField(max_length=255)),
                ('awarded_by', models.CharField(max_length=255)),
                ('date_awarded', models.DateField()),
                ('image', models.ImageField(blank=True, max_length=255, null=True, upload_to='awards/')),
            ],
        ),
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='announcements/')),
            ],
        ),
        migrations.CreateModel(
            name='ResearchAgenda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='research_agenda_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposal_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('engagement_date', models.DateField()),
                ('disengagement_date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('lead_proponent', models.CharField(max_length=255)),
                ('contact_details', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('target_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('partner_community', models.CharField(max_length=255)),
                ('school', models.BooleanField(default=False)),
                ('barangay', models.BooleanField(default=False)),
                ('government_org', models.CharField(blank=True, max_length=255, null=True)),
                ('non_government_org', models.CharField(blank=True, max_length=255, null=True)),
                ('identified_needs_text', models.TextField(blank=True, null=True)),
                ('identified_needs_file', models.FileField(blank=True, null=True, upload_to='Proposals/identified_needs/')),
                ('general_objectives', models.TextField()),
                ('specific_objectives', models.TextField()),
                ('success_indicators', models.TextField()),
                ('cooperating_agencies', models.TextField()),
                ('monitoring_mechanics', models.TextField()),
                ('evaluation_mechanics', models.TextField()),
                ('timetable', models.TextField()),
                ('risk_assessment', models.TextField()),
                ('action_plans', models.TextField()),
                ('sustainability_approaches', models.TextField()),
                ('budget_requirement_text', models.TextField(blank=True, null=True)),
                ('budget_requirement_file', models.FileField(blank=True, null=True, upload_to='Proposals/budget_requirements/')),
                ('directorSignDate', models.DateField(blank=True, null=True)),
                ('VPRESignDate', models.DateField(blank=True, null=True)),
                ('PRESignDate', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved by Director', 'Approved by Director'), ('Approved by VPRE', 'Approved by VPRE'), ('Approved by Barangay', 'Approved by Barangay'), ('Approved by President', 'Approved by President'), ('Partly Approved by Barangay', 'Partly Approved by Barangay'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProposalVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('engagement_date', models.DateField()),
                ('disengagement_date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('lead_proponent', models.CharField(max_length=255)),
                ('contact_details', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('target_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('partner_community', models.CharField(max_length=255)),
                ('school', models.BooleanField(default=False)),
                ('barangay', models.BooleanField(default=False)),
                ('government_org', models.CharField(blank=True, max_length=255, null=True)),
                ('non_government_org', models.CharField(blank=True, max_length=255, null=True)),
                ('identified_needs_text', models.TextField(blank=True, null=True)),
                ('identified_needs_file', models.FileField(blank=True, null=True, upload_to='Proposals/identified_needs/')),
                ('general_objectives', models.TextField()),
                ('specific_objectives', models.TextField()),
                ('success_indicators', models.TextField()),
                ('cooperating_agencies', models.TextField()),
                ('monitoring_mechanics', models.TextField()),
                ('evaluation_mechanics', models.TextField()),
                ('timetable', models.TextField()),
                ('risk_assessment', models.TextField()),
                ('action_plans', models.TextField()),
                ('sustainability_approaches', models.TextField()),
                ('budget_requirement_text', models.TextField(blank=True, null=True)),
                ('budget_requirement_file', models.FileField(blank=True, null=True, upload_to='Proposals/budget_requirements/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('version_status', models.CharField(choices=[('Pending', 'Pending'), ('Approved by Director', 'Approved by Director'), ('Approved by VPRE', 'Approved by VPRE'), ('Approved by Barangay', 'Approved by Barangay'), ('Approved by President', 'Approved by President'), ('Partly Approved by Barangay', 'Partly Approved by Barangay'), ('Rejected', 'Rejected')], default='Pending', max_length=30)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='api.proposal')),
            ],
        ),
        migrations.AddField(
            model_name='proposal',
            name='current_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_proposal', to='api.proposalversion'),
        ),
        migrations.CreateModel(
            name='BarangayApproval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barangay_name', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('sign_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barangay_approvals', to='api.proposal')),
            ],
            options={
                'unique_together': {('proposal', 'barangay_name')},
            },
        ),
    ]
