# Generated by Django 5.0.7 on 2024-11-06 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumnievaluator',
            name='password',
        ),
        migrations.RemoveField(
            model_name='alumnievaluator',
            name='username',
        ),
        migrations.RemoveField(
            model_name='externalparticipantevaluator',
            name='password',
        ),
        migrations.RemoveField(
            model_name='externalparticipantevaluator',
            name='username',
        ),
        migrations.RemoveField(
            model_name='facultyevaluator',
            name='password',
        ),
        migrations.RemoveField(
            model_name='facultyevaluator',
            name='username',
        ),
        migrations.RemoveField(
            model_name='studentevaluator',
            name='password',
        ),
        migrations.RemoveField(
            model_name='studentevaluator',
            name='username',
        ),
    ]
