# Generated by Django 5.0.7 on 2024-10-09 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Barangay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('brgy_name', models.CharField(max_length=100)),
                ('moa', models.TextField()),
            ],
        ),
    ]
