# Generated by Django 5.1.1 on 2024-09-16 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('proposal_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('engagement_date', models.DateField()),
                ('disengagement_date', models.DateField()),
                ('department', models.CharField(max_length=255)),
                ('lead_proponent', models.CharField(max_length=255)),
                ('contact_details', models.CharField(max_length=255)),
                ('project_description', models.TextField()),
                ('target_date', models.DateField()),
                ('location', models.CharField(max_length=255)),
                ('partner_community', models.CharField(max_length=255)),
                ('school', models.BooleanField(default=False)),
                ('barangay', models.BooleanField(default=False)),
                ('government_org', models.CharField(blank=True, max_length=255, null=True)),
                ('non_government_org', models.CharField(blank=True, max_length=255, null=True)),
                ('identified_needs', models.FileField(blank=True, null=True, upload_to='identified_needs/')),
                ('general_objectives', models.TextField()),
                ('specific_objectives', models.TextField()),
                ('success_indicators', models.TextField()),
                ('cooperating_agencies', models.TextField()),
                ('monitoring_mechanics', models.TextField()),
                ('evaluation_mechanics', models.TextField()),
                ('timetable', models.TextField()),
                ('risk_assessment', models.TextField()),
                ('action_plans', models.TextField()),
                ('sustainability_approaches', models.TextField()),
                ('budget_requirement', models.FileField(blank=True, null=True, upload_to='budget_requirements/')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
