# Generated by Django 5.0.7 on 2024-11-13 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='activityschedule',
            name='status',
            field=models.CharField(default='In Progress', max_length=50),
        ),
    ]
