# Generated by Django 5.0.7 on 2024-11-08 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentevaluator',
            old_name='student_email',
            new_name='email',
        ),
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='NonTeachingEvaluator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('evaluator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.evaluatoraccount')),
            ],
        ),
    ]
