# Generated by Django 5.0.7 on 2024-10-09 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_barangay'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangay',
            name='moa',
            field=models.FileField(blank=True, null=True, upload_to='moa_files/'),
        ),
    ]
