# Generated by Django 5.0.7 on 2024-11-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_alumnievaluator_password_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='position',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
