# Generated by Django 5.1.1 on 2024-09-22 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_proposal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomAuthToken',
        ),
    ]
