# Generated by Django 5.0.7 on 2024-09-14 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_announcement_researchagenda'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='accountID',
            new_name='user_id',
        ),
    ]
