# Generated by Django 5.0.7 on 2024-11-19 02:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_account_failed_login_attempts_account_lockout_until'),
        ('api', '0002_activityschedule_activity_objectives_and_more'),
    ]

    operations = [
    ]
