# Generated by Django 5.0.7 on 2024-11-08 15:09

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_student_email_studentevaluator_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='accountType',
            field=models.CharField(default='Proponent', max_length=255),
        ),
        migrations.AlterField(
            model_name='account',
            name='status',
            field=models.CharField(default='Active', max_length=50),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='award_title',
            field=models.CharField(default='Unknown Award', max_length=255),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='awarded_by',
            field=models.CharField(default='Unknown Awarded By', max_length=255),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='awardee',
            field=models.CharField(default='Unknown Awardee', max_length=255),
        ),
        migrations.AlterField(
            model_name='achievement',
            name='date_awarded',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='activity_title',
            field=models.CharField(default='Activity Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='target_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='activityschedule',
            name='target_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='adminaccount',
            name='name',
            field=models.CharField(default='Unknown Admin', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumnievaluator',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='alumnievaluator',
            name='course',
            field=models.CharField(default='Unknown Course', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumnievaluator',
            name='department',
            field=models.CharField(default='Unknown Department', max_length=255),
        ),
        migrations.AlterField(
            model_name='alumnievaluator',
            name='email',
            field=models.EmailField(default='alumni@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='details',
            field=models.TextField(default='Unknown Details'),
        ),
        migrations.AlterField(
            model_name='announcement',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='barangay',
            name='brgy_name',
            field=models.CharField(default='Unknown Barangay', max_length=100),
        ),
        migrations.AlterField(
            model_name='barangayapproval',
            name='barangay_name',
            field=models.CharField(default='Unknown Barangay', max_length=255),
        ),
        migrations.AlterField(
            model_name='barangayapproval',
            name='remarks',
            field=models.TextField(blank=True, default='No Remarks', null=True),
        ),
        migrations.AlterField(
            model_name='barangayapproval',
            name='sign_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='brgyofficialaccount',
            name='name',
            field=models.CharField(default='Unknown Barangay', max_length=255),
        ),
        migrations.AlterField(
            model_name='course',
            name='course_name',
            field=models.CharField(default='Unknown Course', max_length=100),
        ),
        migrations.AlterField(
            model_name='department',
            name='dept_name',
            field=models.CharField(default='Unknown Department', max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='evaluatoraccount',
            name='name',
            field=models.CharField(default='Unknown Evaluator', max_length=255),
        ),
        migrations.AlterField(
            model_name='externalparticipantevaluator',
            name='barangay',
            field=models.CharField(default='Unknown Barangay', max_length=255),
        ),
        migrations.AlterField(
            model_name='externalparticipantevaluator',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='externalparticipantevaluator',
            name='email',
            field=models.EmailField(default='external@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='facultyevaluator',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='facultyevaluator',
            name='department',
            field=models.CharField(default='Unknown Department', max_length=255),
        ),
        migrations.AlterField(
            model_name='facultyevaluator',
            name='email',
            field=models.EmailField(default='faculty@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='facultyevaluator',
            name='position',
            field=models.CharField(default='Unknown Position', max_length=255),
        ),
        migrations.AlterField(
            model_name='nonteachingevaluator',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='nonteachingevaluator',
            name='department',
            field=models.CharField(default='Unknown Department', max_length=255),
        ),
        migrations.AlterField(
            model_name='nonteachingevaluator',
            name='email',
            field=models.EmailField(default='nonteaching@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='nonteachingevaluator',
            name='position',
            field=models.CharField(default='Unknown Position', max_length=255),
        ),
        migrations.AlterField(
            model_name='proponent',
            name='name',
            field=models.CharField(default='Unknown Proponent', max_length=255),
        ),
        migrations.AlterField(
            model_name='proponent',
            name='position',
            field=models.CharField(default='Unknown Position', max_length=255),
        ),
        migrations.AlterField(
            model_name='proponentaccount',
            name='name',
            field=models.CharField(default='Unknown Proponent', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='action_plans',
            field=models.TextField(default='Unknown Action Plans'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='contact_details',
            field=models.CharField(default='00000000000', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='cooperating_agencies',
            field=models.TextField(default='Unknown Cooperating Agencies'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='department',
            field=models.CharField(default='Unknown Department', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='disengagement_date',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='engagement_date',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='evaluation_mechanics',
            field=models.TextField(default='Unknown Evaluation Mechanics'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='general_objectives',
            field=models.TextField(default='Unknown General Objectives'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='lead_proponent',
            field=models.CharField(default='Unknown Lead Proponent', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='monitoring_mechanics',
            field=models.TextField(default='Unknown Monitoring Mechanics'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='partner_community',
            field=models.CharField(default='Unknown Parter Community', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='project_description',
            field=models.TextField(default='Unknown Porject Descriptiojn'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='risk_assessment',
            field=models.TextField(default='Unknown Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='specific_objectives',
            field=models.TextField(default='Unknown Specific Objectives'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='success_indicators',
            field=models.TextField(default='Unknown Success Indicators'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='sustainability_approaches',
            field=models.TextField(default='Unknown Sustainability Approaches'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='target_date',
            field=models.DateField(default='0000-00-00'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='timetable',
            field=models.TextField(default='Unknown Time Table'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='title',
            field=models.CharField(default='Unknown Title', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='action_plans',
            field=models.TextField(default='Action Plans'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='budget_requirement_text',
            field=models.TextField(blank=True, default='Budget Requirements', null=True),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='contact_details',
            field=models.CharField(default='Contact Details', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='cooperating_agencies',
            field=models.TextField(default='Cooperating Agencies'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='department',
            field=models.CharField(default='General Department', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='disengagement_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='engagement_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='evaluation_mechanics',
            field=models.TextField(default='Evaluation Mechanics'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='general_objectives',
            field=models.TextField(default='General Objectives'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='government_org',
            field=models.CharField(blank=True, default='Unknown Government Org', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='identified_needs_text',
            field=models.TextField(blank=True, default='Needs Description', null=True),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='lead_proponent',
            field=models.CharField(default='Lead Proponent', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='location',
            field=models.CharField(default='Unknown Location', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='monitoring_mechanics',
            field=models.TextField(default='Monitoring Mechanics'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='non_government_org',
            field=models.CharField(blank=True, default='Unknown Non-Government Org', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='partner_community',
            field=models.CharField(default='Community Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='project_description',
            field=models.TextField(default='Project Description'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='risk_assessment',
            field=models.TextField(default='Risk Assessment'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='specific_objectives',
            field=models.TextField(default='Specific Objectives'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='success_indicators',
            field=models.TextField(default='Success Indicators'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='sustainability_approaches',
            field=models.TextField(default='Sustainability Approaches'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='target_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='timetable',
            field=models.TextField(default='Timetable'),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='title',
            field=models.CharField(default='Untitled Proposal', max_length=255),
        ),
        migrations.AlterField(
            model_name='proposalversion',
            name='version_number',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='name',
            field=models.CharField(default='Signatory Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='position',
            field=models.CharField(default='Position', max_length=255),
        ),
        migrations.AlterField(
            model_name='signatory',
            name='section',
            field=models.CharField(choices=[('prepared', 'Prepared By'), ('endorsed', 'Endorsed By'), ('concurred', 'Concurred By')], default='prepared', max_length=20),
        ),
        migrations.AlterField(
            model_name='studentevaluator',
            name='contact_number',
            field=models.CharField(default='0000000000', max_length=15),
        ),
        migrations.AlterField(
            model_name='studentevaluator',
            name='course',
            field=models.CharField(default='Unknown Course', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentevaluator',
            name='department',
            field=models.CharField(default='Unknown Department', max_length=255),
        ),
        migrations.AlterField(
            model_name='studentevaluator',
            name='email',
            field=models.EmailField(default='student@example.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='studentevaluator',
            name='student_id',
            field=models.CharField(default='000000', max_length=50),
        ),
    ]
