# Generated by Django 5.0.7 on 2024-11-13 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_activityschedule_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityschedule',
            name='status',
            field=models.CharField(default='In Progress', max_length=50),
        ),
    ]
