# Generated by Django 5.0.7 on 2024-11-19 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_proposal_remarks'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
