# Generated by Django 5.0.7 on 2024-11-19 02:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20241119_1004'),
        ('api', '0003_merge_20241119_1032'),
    ]

    operations = [
    ]
