# Generated by Django 5.0.7 on 2024-11-08 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_account_position'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentevaluator',
            old_name='student_email',
            new_name='email',
        ),
    ]
