# Generated by Django 5.0.7 on 2024-11-19 04:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_merge_20241119_1032'),
        ('api', '0004_alter_proposal_remarks'),
    ]

    operations = [
    ]
