# Generated by Django 5.0.7 on 2024-10-23 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_id_department_dept_id_course'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='dept',
            new_name='dept_id',
        ),
    ]
