# Generated by Django 5.0.7 on 2024-11-08 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_rename_student_email_studentevaluator_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonTeaching',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('contact_number', models.CharField(max_length=15)),
                ('position', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=255)),
                ('evaluator', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.evaluatoraccount')),
            ],
        ),
    ]
