# Generated by Django 5.0.7 on 2024-11-09 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_proposal_research_agendas_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barangayapproval',
            name='barangay_name',
            field=models.CharField(max_length=255),
        ),
    ]
