# Generated by Django 5.0.7 on 2024-09-14 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_customauthtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomAuthToken',
            new_name='CustomToken',
        ),
    ]
