# Generated by Django 5.0.7 on 2024-09-26 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_proposal_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='BRGYSignDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='PRESignDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='VPRESignDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='directorSignDate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='budget_requirement',
            field=models.FileField(blank=True, null=True, upload_to='Proposals/budget_requirements/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='identified_needs',
            field=models.FileField(blank=True, null=True, upload_to='Proposals/identified_needs/'),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved by Director', 'Approved by Director'), ('Approved by VPRE', 'Approved by VPRE'), ('Approved by Barangay', 'Approved by Barangay'), ('Approved by President', 'Approved by President'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
