# Generated by Django 5.0.7 on 2024-11-19 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_merge_20241119_1045'),
        ('api', '0005_merge_20241119_1206'),
    ]

    operations = [
    ]
