# Generated by Django 5.0.7 on 2024-11-08 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_nonteaching'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NonTeaching',
            new_name='NonTeachingEvaluator',
        ),
    ]
