# Generated by Django 5.0.7 on 2024-09-14 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rename_customauthtoken_customtoken'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CustomToken',
            new_name='CustomAuthToken',
        ),
    ]
