# Generated by Django 5.0.7 on 2024-09-14 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_customtoken_customauthtoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='customauthtoken',
            name='refresh_expiration',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customauthtoken',
            name='refresh_key',
            field=models.CharField(blank=True, max_length=40, null=True, unique=True),
        ),
    ]
