# Generated by Django 5.1.1 on 2024-10-01 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_barangayapproval'),
    ]

    operations = [
        migrations.RenameField(
            model_name='barangayapproval',
            old_name='approved_date',
            new_name='sign_date',
        ),
        migrations.RemoveField(
            model_name='proposal',
            name='BRGYSignDate',
        ),
        migrations.AddField(
            model_name='barangayapproval',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='barangayapproval',
            unique_together={('proposal', 'barangay_name')},
        ),
    ]
