# Generated by Django 5.0.7 on 2024-11-19 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_merge_20241119_2205'),
        ('api', '0006_merge_20241119_2232'),
    ]

    operations = [
    ]
