# Generated by Django 5.1.1 on 2024-10-01 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_rename_approved_date_barangayapproval_sign_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Approved by Director', 'Approved by Director'), ('Approved by VPRE', 'Approved by VPRE'), ('Approved by Barangay', 'Approved by Barangay'), ('Approved by President', 'Approved by President'), ('Partly Approved by Barangay', 'Partly Approved by Barangay'), ('Rejected', 'Rejected')], default='Pending', max_length=30),
        ),
    ]
