# Generated by Django 5.0.7 on 2024-10-03 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_proposal_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='proposal',
            old_name='budget_requirement',
            new_name='budget_requirement_file',
        ),
        migrations.RenameField(
            model_name='proposal',
            old_name='identified_needs',
            new_name='identified_needs_file',
        ),
        migrations.AddField(
            model_name='proposal',
            name='budget_requirement_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='proposal',
            name='identified_needs_text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
